### ISSUE TITLE
Average distance graph

### ISSUE THREAD

**Issue by MiztaOak** [MiztaOak/Group55_BachelorsThesis#24]
Implement a graph that is displayed in the bottom UI that displays the average distance from the ligand source for each of the different "bacteria types" in the simulation.

**Comment by r8teful** [comment]
*wink* https://www.youtube.com/watch?v=CmU5-v-v1Qo *wink*

**Comment by MiztaOak** [comment]
Deprioritizing this since I am not sure if this is still relevant.
