### ISSUE TITLE
Collision stuck bouncing

### ISSUE THREAD

**Issue by l0gren** [MiztaOak/Group55_BachelorsThesis#31]
Bacteria that find the wall just keep bouncing against it

**Comment by MiztaOak** [comment]
I have never seen this bug. Does it still happen on the current dev build? And what regulator + environmental settings are you using?

**Comment by l0gren** [comment]
Yeap! ODERegulation and did not change the environmental setting. The reason it doesn't show up is because I removed the smart tumbling, I suspect
